# Generated by Django 5.2.16 on 2026-09-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryadjustment",
            name="mutation_kind",
            field=models.CharField(
                choices=[
                    ("change", "Stock change"),
                    ("set", "Set"),
                ],
                default="change",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="inventoryadjustment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("mutation_kind__in", ["change", "set"])
                ),
                name="inventory_adjustment_mutation_kind_valid",
            ),
        ),
    ]
