# Generated by Django 5.2.16 on 2026-08-02 11:26

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
        ('catalog', '0002_business_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tags', to='businesses.business')),
            ],
            options={
                'ordering': ['name', 'id'],
                'constraints': [models.UniqueConstraint(models.F('business'), django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('name')), name='unique_tag_name_per_business'), models.CheckConstraint(condition=models.Q(('name__regex', '\\S')), name='tag_name_not_blank')],
            },
        ),
    ]
