# Generated by Django 5.2.16 on 2026-08-02 12:08

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
        ('catalog', '0003_business_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProductTypeAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_type_aliases', to='businesses.business')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aliases', to='catalog.businessproducttype')),
            ],
            options={
                'ordering': ['alias', 'id'],
                'constraints': [models.UniqueConstraint(models.F('business'), django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('alias')), name='unique_product_type_alias_per_business'), models.CheckConstraint(condition=models.Q(('alias__regex', '\\S')), name='product_type_alias_not_blank')],
            },
        ),
        migrations.CreateModel(
            name='BusinessTagAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tag_aliases', to='businesses.business')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aliases', to='catalog.businesstag')),
            ],
            options={
                'ordering': ['alias', 'id'],
                'constraints': [models.UniqueConstraint(models.F('business'), django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('alias')), name='unique_tag_alias_per_business'), models.CheckConstraint(condition=models.Q(('alias__regex', '\\S')), name='tag_alias_not_blank')],
            },
        ),
    ]
