# Generated by Django 5.2.16 on 2026-08-02 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
        ('catalog', '0004_business_scoped_aliases'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMaterialFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_material', models.CharField(max_length=80)),
                ('percentage', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('original_text', models.CharField(max_length=160)),
                ('source', models.CharField(choices=[('description', 'Description'), ('manual', 'Manual')], max_length=20)),
                ('confirmation_state', models.CharField(choices=[('confirmed', 'Confirmed')], default='confirmed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_material_facts', to='businesses.business')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_facts', to='catalog.product')),
            ],
            options={
                'ordering': ['product_id', 'canonical_material', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('canonical_material__regex', '\\S')), name='material_canonical_not_blank'), models.CheckConstraint(condition=models.Q(('original_text__regex', '\\S')), name='material_original_text_not_blank'), models.CheckConstraint(condition=models.Q(('percentage__isnull', True), models.Q(('percentage__gte', 1), ('percentage__lte', 100)), _connector='OR'), name='material_percentage_1_to_100_or_null'), models.CheckConstraint(condition=models.Q(('source__in', ['description', 'manual'])), name='material_source_known'), models.CheckConstraint(condition=models.Q(('confirmation_state', 'confirmed')), name='material_confirmation_state_confirmed')],
            },
        ),
    ]
