# Generated by Django 5.2.16 on 2026-08-14

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_product_material_fact"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.CharField(max_length=40)),
                ("color", models.CharField(max_length=80)),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_choices",
                        to="businesses.business",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="choices",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["product_id", "size", "color", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        models.F("product"),
                        django.db.models.functions.text.Lower(
                            django.db.models.functions.text.Trim("size")
                        ),
                        django.db.models.functions.text.Lower(
                            django.db.models.functions.text.Trim("color")
                        ),
                        name="unique_product_choice_per_product",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("size__regex", "\\S")),
                        name="product_choice_size_not_blank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("color__regex", "\\S")),
                        name="product_choice_color_not_blank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("quantity__gte", 0)),
                        name="product_choice_quantity_nonnegative",
                    ),
                ],
            },
        ),
    ]
