# Generated by Django 5.2.16 on 2026-08-14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_product_choice"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="productchoice",
            name="unique_product_choice_per_product",
        ),
    ]
